# Generated by Django 5.1 on 2025-04-01 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ واریز')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ واریز')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='core.account')),
            ],
            options={
                'verbose_name': 'واریز',
                'verbose_name_plural': 'واریزها',
            },
        ),
    ]
