# Generated by Django 5.1 on 2025-03-27 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('account_number', models.CharField(max_length=20, unique=True, verbose_name='شماره حساب')),
                ('id_number', models.CharField(max_length=20, verbose_name='شماره شناسنامه')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('id_copy', models.FileField(blank=True, null=True, upload_to='id_copies/', verbose_name='کپی شناسنامه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتری\u200cها',
            },
        ),
    ]
