# Generated by Django 5.1 on 2025-04-01 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ وام')),
                ('date_issued', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نرخ سود')),
                ('duration_months', models.IntegerField(verbose_name='مدت زمان (ماه)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='customer.customer')),
            ],
            options={
                'verbose_name': 'وام',
                'verbose_name_plural': 'وام\u200cها',
            },
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_installments', models.IntegerField(verbose_name='تعداد اقساط')),
                ('amount_per_installment', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ هر قسط')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='loan.loan')),
            ],
            options={
                'verbose_name': 'طرح قسط',
                'verbose_name_plural': 'طرح\u200cهای قسط',
            },
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ پرداخت')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پرداخت')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_payments', to='loan.loan')),
            ],
            options={
                'verbose_name': 'پرداخت قسط',
                'verbose_name_plural': 'پرداخت\u200cهای قسط',
            },
        ),
    ]
