# Generated by Django 5.1 on 2025-04-01 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='موجودی کل')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='customer.customer')),
            ],
            options={
                'verbose_name': 'موجودی',
                'verbose_name_plural': 'موجودی\u200cها',
            },
        ),
    ]
